# Generated by Django 4.2.1 on 2023-05-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('alternative', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
