# Generated by Django 4.2.1 on 2023-05-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_drug_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='alternative',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
